Interval based classification package refactor
alan-turing-institute/sktime pull request #1583
Opened 2021-11-03 21:23 UTC by MatthewMiddlehurst

Refactor along the lines of #1146 for the interval_based package (RISE, CIF, DrCIF and STSF).
May have changes to already refactored files, as changes to the base class were made in #1517.

TSF has mostly been left alone, as we haven't decided what to do with it yet and some issues could arise with the series_as_features base class. 

Includes a general clean up of docs and tests. RISE could use a bit more cleaning when it comes to documentation and removal of stray commented code at some point.

2021-11-04 09:45 UTC, TonyBagnall submitted a review, later dismissed
this all looks good, I will change experiments.py once the whole refactor is ready for version 9

2021-11-04 09:46 UTC, TonyBagnall commented
not sure why readthedocs is failing, Ive asked in cor-dev channel

2021-11-08 14:51 UTC, chrisholder requested changes

2021-11-08 14:51 UTC, chrisholder commented on sktime/classification/interval_based/_drcif.py
>              raise TypeError(
Is this not a ValueError rather than Type

2021-11-08 14:51 UTC, chrisholder commented on sktime/classification/interval_based/tests/test_rise.py
> +# def print_array(array):
Is this here for future testing or forgot to remove?

2021-11-08 14:51 UTC, chrisholder commented on sktime/classification/interval_based/tests/test_stsf.py
>  # if __name__ == "__main__":
Is this here for future testing or forgot to remove?

2021-11-08 14:51 UTC, chrisholder commented on sktime/classification/interval_based/tests/test_tsf.py
> +# def print_array(array):
Is this here for future testing or forgot to remove?

2021-11-08 22:50 UTC, MatthewMiddlehurst commented
Same as previous refactor PR in regard to test comments, they are there to make it easier to replace results.

2021-11-09 00:09 UTC, chrisholder approved these changes

2021-11-09 11:45 UTC, TonyBagnall approved these changes

2021-11-09 11:45 UTC, merged