[DOC] Update deprecation docs
alan-turing-institute/sktime pull request #1689
Opened 2021-12-03 22:32 UTC by mloning

#### What does this implement/fix? Explain your changes.
* clarifies deprecation docs

2021-12-07 20:07 UTC, mloning reviewed
Self-reviewed, looks all good to me now.

2021-12-08 12:18 UTC, TonyBagnall commented
I'll read all this after the release, since we are in a freeze

2021-12-09 09:46 UTC, TonyBagnall approved these changes

2021-12-11 11:07 UTC, fkiraly commented on docs/source/developer_guide/deprecation.rst
> +In the examples below, the :code:`deprecated` decorator will raise a :code:`FutureWarning` saying that the functionality has been deprecated since version 0.8.0 and will be removed in version 0.10.0.
This statement does not look correct - in the examples, deprecation is since version 0.9.0 and to be removed in 0.11.0, no?

2021-12-11 11:08 UTC, fkiraly requested changes
Looks overall good to me, and I also agree with the proposed policy.

There is one typo in the crucial examples (which may confuse people), so we ought to fix before merge.

2021-12-12 12:04 UTC, mloning commented
Thanks @fkiraly - made the change

2021-12-17 23:42 UTC, fkiraly approved these changes
looks good now, thanks

2021-12-17 23:43 UTC, merged