Fixes prophet bug concerning the internal change of exogenous X
alan-turing-institute/sktime pull request #1711
Opened 2021-12-06 22:15 UTC by kejsitake

#### Reference Issues/PRs

Fixes https://github.com/alan-turing-institute/sktime/issues/1673

#### What does this implement/fix? Explain your changes.

Creates a copy of X in _Prophet_Adapter before changes are made to it.
Checks if X contained a column ds were already implemented in _merge_X, so I didn't implement a new one
#### Does your contribution introduce a new dependency? If yes, which one?
No

2021-12-06 22:45 UTC, aiwalter reviewed
There are already below 2 `if X is not None`. Can we include it there? @fkiraly should we even put it into base class and also copy `y`?

2021-12-07 00:01 UTC, fkiraly requested changes
@kejsitake, thanks!

This is in-principle a fix, but looking at the code I noticed there is another problem. If the series passed *does* have the `ds` column, the forecaster raises an error, which it shouldn't. Also, the `X.copy()` are hard to keep track of.

I would address this as follows:
* write a functions `df_to_prophet` which takes `X` and does not have any side effects on it.
* `df_to_prophet` moves index of `X` to `ds` column. If a `ds` column is already present, it renames it to a name that doesn't exist yet in the columns. For instance, the longest column name plus an underscore or similar.
* the function is applied whenever `X` is passed.

2021-12-07 00:02 UTC, aiwalter approved these changes

2021-12-07 00:07 UTC, aiwalter commented
I think I would not rename a column, thats not intuitive to me and unexpected. Especially bcz that ds column probably contains an index already, which will then raise an error but for a different column name?

2021-12-07 00:17 UTC, fkiraly commented
> I think I would not rename a column, thats not intuitive to me and unexpected. Especially bcz that ds column probably contains an index already, which will then raise an error but for a different column name?

Can you elaborate?

I thought prophet wants the index in the `ds` column, not in the index.
All `sktime` forecasters work fine if a column is already named `ds` (a variable column). To make prophet work fine in that case too, an existing `ds` has to be renamed to make place for the index which is renamed to `ds`.

Otherwise the prophet forecasters fails when a `ds` column is already present?

2021-12-07 00:21 UTC, fkiraly commented
> Especially bcz that ds column probably contains an index already, which will then raise an error but for a different column name?

Could you explain: what would raise an error if `ds` is there already?

2021-12-07 00:22 UTC, fkiraly commented
signing off for today - and I'd be fine with the fix as is, @kejsitake, @aiwalter.
It fixes the bug that was reported, although not the problem what happens if `X` already has a `ds` column.
I'd say to take the pressure off the 0.9.0, let's just merge it like this, and open an issue that captures the problem if `ds` is already a column in `X`.

2021-12-07 00:52 UTC, kejsitake commented
I created another bug for the issue that remains. I can work on it, but are not very sure with which approach we want to move forward with.

2021-12-07 07:31 UTC, aiwalter commented
thx @kejsitake ! :) renaming an existing columns `ds` to sth e.g. `my_ds` could make issues when `ds` already contains an index. `fbprophet` users might do this by accident as they are used to this format. So that means we would have two index columns then and I guess `Prophet` would raise an error (and should) that there is a non-numeric column. This column has now name `my_ds` and users does not understand where this is coming from. So if we are already checking if `ds` exists and raise an error, I dont see a need for a change.

2021-12-07 11:06 UTC, fkiraly commented
>I created another bug for the issue that remains. I can work on it, but are not very sure with which approach we want to move forward with.

Yes, I think that's the best thing. Let's merge the fix for *this bug*, and have a separate discussion how we fix the remaining issue - it's closely related but distinct.

2021-12-07 11:07 UTC, fkiraly approved these changes
bug should be fixed now; will have to fix and refactor further (see discussion above) but it's a separate PR

2021-12-07 11:07 UTC, fkiraly commented
appveyor timed out but didn't fail

2021-12-07 11:08 UTC, merged