Numba based knn
alan-turing-institute/sktime pull request #1761
Opened 2021-12-15 07:53 UTC by TonyBagnall

draft for now, I will expand the explanation later, but primarily this

1. swaps cython for numba
2. resolves the fit/_fit inheritance problem.

(2) may be sub optimal in design, the alternative is to wrap it. This does work though.

2021-12-24 12:14 UTC, fkiraly commented
is this still a draft, @TonyBagnall, or ready for review?
PR description says draft, but PR says it's not a draft.

2021-12-24 12:44 UTC, TonyBagnall commented
@fkiraly feel free to review, looking for opinions on how to do this, preferably with code :)

2021-12-31 10:31 UTC, chrisholder commented on sktime/classification/distance_based/tests/test_time_series_neighbors.py
> -    "erp": 19,
This lower accuracy than before ill make a note and try fix

2021-12-31 10:31 UTC, chrisholder commented on sktime/classification/distance_based/_time_series_neighbors.py
> +            self.metric = distance_factory(X[0], X[0], metric=self.distance, window=10)
Ill refactor this to use params

2022-01-03 17:09 UTC, TonyBagnall commented
@fkiraly can you express an opinion as to whether this will do for conforming to fit/_fit? I happy for it to be redone differently at a later date, but if you really dont like this way of doing it I will revert to its current state and just put in the cython version changes without update for fit/_fit

2022-01-05 10:05 UTC, fkiraly requested changes
Reviewing this for interface compliance upon request by @TonyBagnall.

Re. `fit`, `predict`, etc - I think this is hacky but in-principle not wrong.
However, I feel we should do a `**kwargs` pass-through, that seems safer in terms of being upwards compatible (e.g., for additional arguments to `fit` etc). That is,

```python
def predict(self, **kwargs):
    return BaseClassifier.predict(self, **kwargs)
```

2022-01-05 13:41 UTC, TonyBagnall commented
> Reviewing this for interface compliance upon request by @TonyBagnall.
> 
> Re. `fit`, `predict`, etc - I think this is hacky but in-principle not wrong. However, I feel we should do a `**kwargs` pass-through, that seems safer in terms of being upwards compatible (e.g., for additional arguments to `fit` etc). That is,
> 
> ```python
> def predict(self, **kwargs):
>     return BaseClassifier.predict(self, **kwargs)
> ```

done that, happy if someone wants to adopt a better solution, but this is the simplest way of conforming for the problematic classifiers I feel, especially those no one wants to own.

2022-01-06 10:51 UTC, fkiraly approved these changes
Happy with this, interface-wise.

Before you merge, can you check what that new line added to `.gitignore` is, please? What is that about, is it necessary?

2022-01-07 21:23 UTC, merged

2022-01-07 21:23 UTC, TonyBagnall commented
its passed apveyor before, Im putting this in before it need another update, been trying for a week!