[ENH] full support for `Panel.numpyflat` mtype in `datatypes` module, checks/conversions
alan-turing-institute/sktime pull request #1772
Opened 2021-12-18 13:46 UTC by fkiraly

This PR adds full checking and conversion support for the `numpyflat` (2D numpy array) mtype for `Panel` data... because @TonyBagnall insists on it 😄 

More specifically, this adds:
* checking routines for `numpyflat`
* conversion between `numpyflat` and any other `Panel` mtype currently supported
* fixture examples for the `numpyflat` mtype

Existing tests automatically cover both checks and conversions, nothing needed to be added there.

2021-12-31 10:17 UTC, chrisholder requested changes

2021-12-31 10:17 UTC, chrisholder commented on sktime/datatypes/_panel/_check.py
>  def check_dflist_Panel(obj, return_metadata=False, var_name="obj"):
Rename to check_dflist_panel

2021-12-31 10:17 UTC, chrisholder commented on sktime/datatypes/_panel/_check.py
>      check_res = [check_pdDataFrame_Series(s, return_metadata=True) for s in obj]
Rename check_pdDataFrame_Series to check_pd_dataframe_series

2021-12-31 10:17 UTC, chrisholder commented on sktime/datatypes/_panel/_check.py
>  def check_numpy3D_Panel(obj, return_metadata=False, var_name="obj"):
rename check_numpy3d_panel

2021-12-31 10:17 UTC, chrisholder commented on sktime/datatypes/_panel/_check.py
> +def check_numpyflat_Panel(obj, return_metadata=False, var_name="obj"):
Rename check_numpyflat_panel

2021-12-31 10:17 UTC, chrisholder commented on sktime/datatypes/_panel/_convert.py
> +def from_numpy3D_to_numpyflat(obj, store=None):
Rename from_numpy3d_to_numpyflat

2021-12-31 10:17 UTC, chrisholder commented on sktime/datatypes/_panel/_convert.py
> +def from_numpyflat_to_numpy3D(obj, store=None):
rename from_numpyflat_to_numpy3d

2022-02-15 23:12 UTC, fkiraly commented
@chrisholder, your comments should be addressed.

2022-03-20 09:37 UTC, merged