[DOC] missing get_test_params in transformer extension template
alan-turing-institute/sktime pull request #1774
Opened 2021-12-18 18:03 UTC by fkiraly

This PR adds the missing `get_test_params` function in the transformer extension template.

2021-12-23 14:04 UTC, TonyBagnall commented
this still branch still has the old classifier tags in it. these have changed to "X_inner_mtype": "numpy3D",

2021-12-24 12:12 UTC, fkiraly commented
well, that should be resolved with an update from `main`, doing this now

2021-12-24 12:13 UTC, fkiraly commented
done, is it resolved by update from main? If not, then you (or I) need to update the tag names in a separate PR.

2021-12-30 12:12 UTC, fkiraly commented
@TonyBagnall, your issue should be fixed, kindly have a look.

2021-12-30 16:06 UTC, chrisholder requested changes

2021-12-30 16:06 UTC, chrisholder commented on extension_templates/transformer.py
> +    @classmethod
Make this static rather than class you don't use the cls instance in any of the examlpes i've seen

2021-12-30 16:37 UTC, chrisholder approved these changes

2021-12-30 20:58 UTC, merged