Update extension template for predict_quantiles
alan-turing-institute/sktime pull request #1780
Opened 2021-12-19 12:55 UTC by kejsitake

#### What does this implement/fix? Explain your changes.

Updates the extension template to account for changes introducing predict_quantiles.
#### Does your contribution introduce a new dependency? If yes, which one?

No

#### Any other comments?

This was included in another PR https://github.com/alan-turing-institute/sktime/pull/1579, but I am separating to make review easier. I have fixed some of the issues mentioned there.

2021-12-19 14:25 UTC, fkiraly commented on extension_templates/forecasting.py
> +        # in the future can be changed to capability:predict_quantiles
bit unclear what this means to the person who wants to implement the forecaster. Perhaps say sth like "deprecated and will be renamed to `capability:predict_quantiles` in 0.11.0"?

2021-12-19 14:25 UTC, fkiraly requested changes
looks good!

Some comments:
* docstring at the top should also be updated
* one comment about deprecation

2021-12-19 14:54 UTC, kejsitake commented
Hi! Thank you for the comments. 

I made these changes and also removed the `pred_int` and `alpha` arguments from `_update_predict_single` and `_predict_moving_cutoff`. Please let me know if this isn't correct.

2021-12-20 19:23 UTC, fkiraly commented on extension_templates/forecasting.py
> +            Forecasting horizon, default = y.index (in-sample forecast)
there is no `y` here, so the default does not seem to make sense - or does it and I'm missing sth?
If this is a typo, please remove the "default" part.

2021-12-20 19:24 UTC, fkiraly submitted a review, later dismissed
look good now.

I left one comment on the default `fh`, please fix if that's a typo.

2021-12-20 21:38 UTC, kejsitake commented
Fixed the typo! Thank you for the comments!

2021-12-21 11:21 UTC, fkiraly requested changes
Thanks, looks great!

I have one more request, looking through this.
I don't think we should import from private modules here, i.e., the `DEFAULT_ALPHA`.

How I would avoid it is to set the default in the `_predict_quantiles` to `None` or, perhaps better, `0.5`. In the body of the function, explain that `alpha` is guaranteed to be a float or list of float by `predict_quantiles` calling this function, which is by default the `DEFAULT_ALPHA` coming from `predict_quantiles`.

2021-12-21 23:49 UTC, kejsitake commented
I believe I made this changes. I will keep in mind to include `DEFAULT_ALPHA` in the other PR refactoring `predict_quantiles`. Thank you!

2021-12-22 00:12 UTC, fkiraly requested changes
Great, thanks!

I noticed another thing, unfortunately, sorry for the bits-and-pieces here.

The docstring of `_predict_quantiles` is incorrect in describign the return, `pred_quantiles`. This is incorrectly referring to coverage, i.e., to the input of `_predict_interval`. Instead, it shoudl be referring to `alpha`.

2021-12-22 07:56 UTC, kejsitake commented
I changed the docstring and tried to read through the file for additional issues, could only spot some deprecated args in `_update.` But please let me know if there is anything else.

2021-12-22 16:36 UTC, fkiraly approved these changes
yes, looks great now - thanks!

2021-12-22 16:36 UTC, merged