[ENH] Change default of percentage error functions #1986
alan-turing-institute/sktime pull request #2069
Opened 2022-02-15 15:10 UTC by ciaran-g

Fixes #1986 introduced deprecation in percentage error functions for v.011.0 to precede a change of the default value for `symmetric` from `True` to `False` in v.012

#### Reference Issues/PRs

Fixes #1986 

#### What does this implement/fix? Explain your changes.

Added depreciation notice for changing default in percentage error functions

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

- correct use of the `@deprecate' function

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

2022-02-15 18:44 UTC, fkiraly requested changes
@ciaran-g, there´s one linting failure coming from unsorted imports, otherwise looks good

2022-02-18 14:26 UTC, fkiraly commented
I'm not sure what is happening with all the tests here - some interaction with the deprecation decorator??

2022-02-22 14:56 UTC, ciaran-g commented
Hi @fkiraly - just checked the notebook tests. Hopefully the previous commit addressed the problem, but I'm not sure if it's the best way.

The tests were failing because there was an error thrown in the 01_forecasting notebook when calling this model tuning function
```
gscv = ForecastingGridSearchCV(forecaster=pipe, param_grid=param_grid, cv=cv, n_jobs=-1)
gscv.fit(y_train)
```
The deprecation decorator was causing an error with the default parallel backend in joblib. Basically it was failing to pickle the results. Changing the default parallel backend from `backend='loky'` to `backend='threading'` seems to do the trick for me anyway.

2022-02-22 23:10 UTC, fkiraly commented
@ciaran-g, how weird - thanks for tracking this down!

Regarding the change in the grid search, we should not just change the backend without warning - this would also be something that requires deprecation!

Instead, I would introduce a parameter for the parallelization back-end, if it does not exist, and change it in the notebook and/or test cases - but not in the default.

That way, we don't risk to break user code that uses instances of the grid search estimator.

2022-02-23 12:38 UTC, ciaran-g commented
Good shout Franz, just updated! Introduced the `backend` parameter, changed the call on the notebook, and the ForecastingGridSearchCV docstring example

2022-02-23 17:48 UTC, fkiraly commented on sktime/forecasting/model_selection/_tune.py
> +        'loky' is used by default.
confusing - is it None or `"loky"`? Suggest: to avoid confusion, use the "effective" default which is `"loky"`.

2022-03-02 09:30 UTC, fkiraly requested changes
with all the problems the decorators cause:

I'd suggest to move away from use of `deprecated` and instead raise a warning inside the function. Then everything should work again...

2022-03-02 14:08 UTC, ciaran-g commented
updated @fkiraly! left the `backend` argument open to the user, thought that would be useful anyway

2022-03-06 13:21 UTC, fkiraly requested changes
I think this is good - would you mind reverting your changes to the forecaster tutorial?
As far as I can see, no content is changed or added.

2022-03-06 14:36 UTC, fkiraly approved these changes
I just did that if you don't mind, and will merge if/once tests pass.

2022-03-06 19:33 UTC, merged