[DOC] replace gitter mentions by appropriate links, references
alan-turing-institute/sktime pull request #2187
Opened 2022-03-09 16:38 UTC by TonyBagnall

as per the agreement at CC meeting on 8/3/22, I have purged all references I could find to Gitter.

2022-03-09 17:47 UTC, fkiraly commented on docs/source/developer_guide/git_workflow.rst
> +   If you get stuck, chat with us on `Discord`_.
I would say, primarily slack, on the `#contributors` channel. We are much more active on slack imo.

2022-03-09 17:47 UTC, fkiraly commented on docs/source/get_involved/contributing.rst
> +   If you get stuck, chat with us on `Discord`_.
slack as well.

2022-03-09 17:47 UTC, fkiraly requested changes
I would actually point to slack for anything developer related.

I would also add references to the community collaboration sessions on Fridays, where appropriate.

2022-03-10 10:19 UTC, TonyBagnall commented
> I would actually point to slack for anything developer related.
> 
> I would also add references to the community collaboration sessions on Fridays, where appropriate.

I'm happy for you to add anything you want, I was just trying to action the removal of gitter, that is all this PR is meant to do

2022-03-10 22:58 UTC, fkiraly commented
> I'm happy for you to add anything you want, I was just trying to action the removal of gitter, that is all this PR is meant to do

Well, if we're already doing it, imo, let's do it "right" and funnel new contributors towards slack primarily.

2022-03-11 00:26 UTC, fkiraly commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://discord.com/invite/gqSab2K
```suggestion
    url: https://join.slack.com/t/sktime-group/shared_invite/zt-62i7aejn-vXc3nOWF26S_P3VXFPWisQ
```

2022-03-11 00:26 UTC, fkiraly commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: Chat with the sktime community on Discord
```suggestion
    about: Chat with the sktime community on Slack
```

2022-03-11 00:31 UTC, fkiraly commented on docs/source/get_involved/contributing.rst
>  .. _discord: https://discord.com/invite/gqSab2K
```suggestion
.. _discord: https://discord.com/invite/gqSab2K
.. _slack: https://join.slack.com/t/sktime-group/shared_invite/zt-62i7aejn-vXc3nOWF26S_P3VXFPWisQ
```

2022-03-11 00:32 UTC, fkiraly commented on docs/source/get_involved/contributing.rst
> +   If you get stuck, chat with us on `Discord`_.
```suggestion
   If you get stuck, chat with us on `Slack`_, or join one of the community sessions on `Discord`_.
```

2022-03-11 00:32 UTC, fkiraly commented on docs/source/developer_guide/git_workflow.rst
> +   If you get stuck, chat with us on `Discord`_.
```suggestion
   If you get stuck, chat with us on `Slack`_, or join one of the community sessions on `Discord`_.
```

2022-03-11 00:32 UTC, fkiraly commented on docs/source/get_involved/contributing.rst
> +   If we have missed anything, please `raise an issue <https://github.com/alan-turing-institute/sktime/issues/new/choose>`_ or chat with us on `Discord`_.
```suggestion
   If we have missed anything, please `raise an issue <https://github.com/alan-turing-institute/sktime/issues/new/choose>`_ or chat with us on Slack`_.
```

2022-03-11 00:33 UTC, fkiraly commented on docs/source/get_involved/mentoring.rst
> +If you have any questions or get stuck, please don't hesitate to `chat with us <https://discord.com/invite/gqSab2K>`_ or email us at info@sktime.org.
```suggestion
If you have any questions or get stuck, please don't hesitate to `chat with us on slack <https://join.slack.com/t/sktime-group/shared_invite/zt-62i7aejn-vXc3nOWF26S_P3VXFPWisQ>`_, join on of our collaborative community sessions on `discord <https://discord.com/invite/gqSab2K>`_, or email us at info@sktime.org.
```

2022-03-11 00:34 UTC, fkiraly requested changes
I've made explicit suggestions how to change this to "slack primary" pointers.

You just need to accept the suggestions, and all shall be fine (I hope), so no additional work on you.

2022-03-11 09:15 UTC, fkiraly commented
> I'm happy for you to add anything you want,

Do you mind accepting the suggestions? They replace discord by slack whenever developer content is the context.

2022-03-11 11:59 UTC, fkiraly commented
oops, something is broken now, let me check

2022-03-11 12:00 UTC, fkiraly commented
?? seems like there is no error message, readthedocs build just didn´t start. Just restart it?

2022-03-11 20:23 UTC, fkiraly approved these changes
Restarted readthedocs, looks good.

2022-03-11 20:26 UTC, fkiraly requested changes
Actually, no:

the links in `contributing.rst` don´t point anywhere: discord is missing, and slack has the wrong capitalization. Let me fix that.

2022-03-11 21:16 UTC, fkiraly approved these changes
I think, all fixed now.

2022-03-11 21:17 UTC, merged