[MNT] Removed _update from STLForecaster
alan-turing-institute/sktime pull request #2471
Opened 2022-04-14 09:46 UTC by aiwalter

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

2022-04-14 11:28 UTC, aiwalter commented
@fkiraly seems the PR #2466 did not resolve the issue?

2022-04-27 16:34 UTC, fkiraly commented
This should do it!
https://github.com/alan-turing-institute/sktime/pull/2557

2022-04-30 22:32 UTC, fkiraly commented on extension_templates/forecasting.py
> +                    - Only mandatory to for compositions, see e.g.  STLForecaster
I think this is misleading, people would ready this as "not mandatory if not a composition", or not know what a composition is. So I would recommend to remove this.
I would add explanatory text in the body instead, about `update_params=False`.

2022-04-30 22:34 UTC, fkiraly commented on sktime/forecasting/trend.py
> +            self.seasonal_ = pd.Series(self._stl.seasonal, index=y.index)
seems incorrect to me, because `y` is only the new data, not all data

2022-05-01 08:07 UTC, fkiraly requested changes
Yes, this is the right fix imo!

I would kindly ask you to change the comments in the extension template - details like that should not be in the table of contents, but in the explanation of what to fill in in `_update`.

2022-08-06 21:44 UTC, fkiraly commented
this can't be replaced by the default because we have three components, which need to be updated by specific `y` (not by the one passed to `update`.

2022-08-06 21:44 UTC, closed without merging