[ENH] Add DummyClassifier
alan-turing-institute/sktime pull request #2707
Opened 2022-05-27 23:11 UTC by ZiyaoWei

Fixes #2507.

#### What does this implement/fix? Explain your changes.

Adds a DummyClassifier that wraps over a sklearn DummyClassifier and inherits from BaseClassifier.

#### Does your contribution introduce a new dependency? If yes, which one?

No

#### What should a reviewer concentrate their feedback on?

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [ ] I've added unit tests and made sure they pass locally.
- [ ] The PR title starts with either [ENH], [DOC] or [BUG] indicating whether the PR topic is related to enhancement, documentation or bug

##### For new estimators
- [ ] I've added the estimator to the online documentation.
- [ ] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

2022-05-27 23:14 UTC, ZiyaoWei commented
@fkiraly - so internally this didn't create any fake data and instead just passed the data directly to the sklearn DummyClassifier - is that okay?

Also, I guess this is the only one where sklearn has a direct equivalent, but would we want any other dummy implementations?

2022-05-28 11:54 UTC, fkiraly requested changes
Thank you!

Currently, your classifier does not seem to pass any tests.

You need to make sure you adhere to the `sktime` specifications. For instance, the `X` passed are 3D numpy array, or whatever is specified in the `X_inner_mtype`.

Since the `DummyClassifier` ignores `X`, you could just create an `sklearn` array of suitable 2D shape to avoid formatting issues.

Further, `__init__` should not have an args catch.

2022-05-28 23:37 UTC, ZiyaoWei commented
@fkiraly - thanks! I didn't realize the test suite enforces these, will fix later. Sorry for the back and forth!

2022-05-30 13:50 UTC, ZiyaoWei commented
It turns out I forgot to call the super class initializer - not a Python expert by any means!

@fkiraly - it seems now it passes the tests; however, I didn't create any dummy input, and since the input is converted by the boilerplate in `BaseClassifier` and then ignored the underlying calls to sklearn still works. Am I missing something?

2022-06-01 20:43 UTC, fkiraly requested changes
Thanks, looks great!

I would kindly request one change:
This should also work for unequal length series, but by virtue of the conversion to `numpy3D` the classifier only works for equal length series. How to deal with that, see above.

Let me know if you are not sure what I mean.

2022-06-09 00:30 UTC, ZiyaoWei commented on sktime/classification/dummy/_dummy.py
> +        self.sklearn_dummy_classifier.fit(X, y)
Thanks! I thought this has the advantage of not having to create anything so it's more efficient, but I guess that would be unnecessary optimization and creating a dummy value makes the code more readable - will change.

2022-06-09 01:12 UTC, ZiyaoWei commented on sktime/classification/dummy/_dummy.py
> +        "capability:missing_values": True,
I had this initially but weren't sure how to make it work, and later forgot to add it back. Thanks for the pointers!

2022-06-11 13:20 UTC, fkiraly commented
@ZiyaoWei, let me know once ready for re-review.
There is also a conflict with `.all-contributorsrc`, kindly resolve that or I cannot trigger CI/CD

2022-06-12 12:54 UTC, fkiraly approved these changes
@ZiyaoWei, thanks a lot! Good to go now!

I made some minor change before merge:

* fixing the merge conflict in the contributor file
* adding a docstring, copy-paste from sklearn with credit attribution

2022-06-12 14:07 UTC, merged

2022-06-12 18:21 UTC, ZiyaoWei commented
@fkiraly - thanks for the reviews and the cleanup fixes,  happy to contribute!