[DOC] Adds to the troubleshoot section of website
alan-turing-institute/sktime pull request #2786
Opened 2022-06-11 12:04 UTC by AurumnPegasus

#### Reference Issues/PRs

Adds to the documentation according to #2770 

#### What does this implement/fix? Explain your changes.

Added the solution to the troubleshoot section of ```installation.rst```.

#### PR checklist

##### For all contributions
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

2022-06-11 13:11 UTC, fkiraly commented on docs/source/installation.rst
> +- Solution: use inverted commas:
called quotation mark

2022-06-11 13:13 UTC, fkiraly requested changes
Thanks!

Although this might not be the right location, as the section above does not contain an instance of `all_extras,dev` as args?

2022-06-12 09:05 UTC, AurumnPegasus commented
> Thanks!
> 
> Although this might not be the right location, as the section above does not contain an instance of `all_extras,dev` as args?

I will put it next to the place the command is given itself?

2022-06-12 12:22 UTC, fkiraly commented
yes, that sounds like the best idea, or in an adjacent section.

2022-06-13 10:52 UTC, AurumnPegasus commented on docs/source/installation.rst
> +- Solution: use inverted commas:
Updated.

2022-06-13 10:53 UTC, AurumnPegasus commented
@fkiraly 
Made changes as requested, please check and let me know if anything else is required

2022-06-15 09:08 UTC, fkiraly commented on docs/source/installation.rst
> +A frequent issue encountered when downloading the dev/all_extras version of dependencies
(it's also not a frequent issue)

2022-06-16 10:54 UTC, fkiraly commented on docs/source/installation.rst
> +A frequent issue encountered when downloading the dev/all_extras version of dependencies
Thanks!

2022-06-16 10:55 UTC, fkiraly approved these changes
Looks good now, thanks!

2022-06-16 21:19 UTC, merged