[ENH] Pass frequency explicitly to `_make_fh` function
alan-turing-institute/sktime pull request #2885
Opened 2022-06-28 07:14 UTC by khrapovs

#### Reference Issues/PRs

Partially addresses https://github.com/alan-turing-institute/sktime/issues/1750.

#### What does this implement/fix? Explain your changes.

Pass frequency explicitly to `_make_fh` function so that it is no longer extracted from `cutoff` argument. This argument may be `pd.Timestamp` and its `freq` attribute will be deprecated in the future.

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [ ] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [X] I've added unit tests and made sure they pass locally.
- [X] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

2022-06-28 07:15 UTC, khrapovs commented
This PR has an overlap with https://github.com/alan-turing-institute/sktime/pull/2834 which should be merged first.

2022-07-08 16:41 UTC, fkiraly commented
Question: in the tests, should `fh` not be created without a `freq`?

Because the `fh` that the user makes will typically not have it.

Having the option to pass `freq` makes sense though - for this, would a `fh.freq = freq` at the end be sufficient?

2022-07-08 18:23 UTC, khrapovs commented
> Question: in the tests, should `fh` not be created without a `freq`?
> Because the `fh` that the user makes will typically not have it.

Whenever `fh` is converted to absolute/relative, there must be a `freq` attribute present. At the current state of `main` it can be either at construction or from a proper `cutoff`. Passing string at construction seems to me personally the most clear unambiguous and explicit way to do that. 

> Having the option to pass `freq` makes sense though - for this, would a `fh.freq = freq` at the end be sufficient?

This is 100% equivalent to `ForecastingHorizon(..., freq=freq)`.

2022-07-08 18:34 UTC, fkiraly commented
>> Having the option to pass `freq` makes sense though - for this, would a `fh.freq = freq` at the end be sufficient?

>This is 100% equivalent to `ForecastingHorizon(..., freq=freq)`.

Yes, indeed it is!

2022-07-08 18:35 UTC, fkiraly commented on sktime/forecasting/base/tests/test_fh.py
> +        freq=infer_freq(y_train),
with the change, line 91 is redundant!

2022-07-08 18:35 UTC, fkiraly commented on sktime/forecasting/model_selection/tests/test_split.py
> +        freq=infer_freq(y),
I think we want this test to be "stronger", i.e., to work without `freq` pased to `_make_fh`

2022-07-08 18:40 UTC, fkiraly requested changes
The general theme behind my change request is:

If `freq` is not passed to `_make_fh`, the initial `fh` knows less, and the test is hence "stronger", because it also tests that `fh` "learns" the `freq` from the objects it interacts with.

I think we should always carry out the "stronger" version of the test, since that is typically what the user will do, in a case where it will not trigger the deprecated functionality internally.

These are, I think the following tests:
* `test_predict_time_index`
* `test_predict_time_index_with_X`
* `test_predict_time_index_in_sample_full`

(the other ones do not matter since `fh` is not modelling "user constructed" behaviour)

2022-07-16 12:44 UTC, khrapovs commented
Resolved by https://github.com/alan-turing-institute/sktime/pull/2965

2022-07-16 12:44 UTC, closed without merging