[ENH] Msm distance cleanup
alan-turing-institute/sktime pull request #2964
Opened 2022-07-10 02:15 UTC by chrisholder

This PR cleans up msm redundent functions and improves docstrong

#### Reference Issues/PRs

#### What does this implement/fix? Explain your changes.

MSM was missing docstrings for variables and additionally there was redundent functions in the file which have been removed.
Additionally code has been simplified using built in python functions.

#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

#### Any other comments?

#### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/alan-turing-institute/sktime/blob/main/.all-contributorsrc).
- [x] Optionally, I've updated sktime's [CODEOWNERS](https://github.com/alan-turing-institute/sktime/blob/main/CODEOWNERS) to receive notifications about future changes to these files.
- [x] I've added unit tests and made sure they pass locally.
- [x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG] indicating whether the PR topic is related to enhancement, maintenance, documentation, or bug.

##### For new estimators
- [x] I've added the estimator to the online documentation.
- [x] I've updated the existing example notebooks or provided a new one to showcase how my estimator works.

2022-07-11 13:13 UTC, TonyBagnall requested changes
so minor points.

2022-07-11 13:13 UTC, TonyBagnall commented on sktime/classification/distance_based/tests/test_time_series_neighbors.py
>      """Test function for elastic knn, to be reinstated soon."""
we can remove the "to be reinstated soon"?

2022-07-11 13:13 UTC, TonyBagnall commented on sktime/distances/tests/_expected_results.py
> +    "msm": [5.0, 6.828557434224288, None],
why have the expected results changed? Is it the different default c value? Can we also replace the None?

2022-07-22 06:34 UTC, TonyBagnall approved these changes

2022-07-22 06:34 UTC, TonyBagnall submitted a review, later dismissed

2022-08-21 22:10 UTC, fkiraly approved these changes
Looks like sensible changes.

2022-08-21 22:10 UTC, merged