Dobin basis transformation
alan-turing-institute/sktime pull request #3373
Opened 2022-09-01 23:36 UTC by KatieBuc

Implementation of Issue #3371

Distance based Outlier BasIs using Neighbors (DOBIN) is a new approach to select a set of basis vectors tailored for outlier detection. The transformation outputs are the new coordinate system (such that outliers are best retained in lower the dimensional feature space).

FYI @Lovkush-A @fkiraly @lmmentel

2022-09-07 07:19 UTC, KatieBuc commented
@fkiraly @aiwalter @Lovkush-A @lmmentel this is ready for review :)

2022-09-07 08:10 UTC, lmmentel requested changes

2022-09-07 08:10 UTC, lmmentel commented on sktime/transformations/series/dobin.py
> +    influence on Euclidean distances. The original implelemtation -[1] uses
```suggestion
    influence on Euclidean distances. The original implelemtation _[1] uses
```

2022-09-07 08:10 UTC, lmmentel commented on sktime/transformations/series/dobin.py
> +    from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler
```suggestion
    ``from sklearn.preprocessing import MinMaxScaler, RobustScaler, StandardScaler``
```

2022-09-07 08:10 UTC, lmmentel commented on sktime/transformations/series/dobin.py
> +    MinMaxScaler normalization.
```suggestion
    ``MinMaxScaler`` normalization.
```

2022-09-07 08:10 UTC, lmmentel commented on sktime/transformations/series/dobin.py
> +    frac : int, float (default=0.95)
Since it's a quantile maybe leave `int` out and keep `float` only

2022-09-07 08:10 UTC, lmmentel commented on sktime/transformations/series/dobin.py
> +        as 5% of the number of observations with a cap of 20.
Any chance you could reformulate what the default value is, it's a bit confusing.

2022-09-07 08:10 UTC, lmmentel commented on sktime/transformations/series/dobin.py
> +
missing docstring

2022-09-07 08:10 UTC, lmmentel commented on sktime/transformations/series/dobin.py
> +
missing docstring

2022-09-07 08:10 UTC, lmmentel commented on sktime/transformations/series/dobin.py
> +    """Calculate distance between close pairs."""
Could you expand the docstring to cover argument types and descriptions and the output?

2022-09-09 06:24 UTC, KatieBuc commented
@fkiraly ready to merge?

2022-09-11 21:03 UTC, fkiraly requested changes
In-principle happy with this.

My only change request is to ensure the docstring references the algorithm precisely.
Can you describe clearly what thet output of `transform` is, in the class docstring?

Also, what are "basistors"? Is that at typo or a term from the paper, if the latter it needs to be defined.

2022-09-13 09:25 UTC, lmmentel approved these changes

2022-09-13 11:10 UTC, fkiraly requested changes
Thanks!

In the class doc-string, could you please add:
* a reference to precisely which algorithm is implemented (algorithm X from page Y)
* an explanation of how the algorithm differs from the reference, e.g., normalization
* optimally: how parameters map onto symbols in the paper
* how the outliers are encoded as output of `transform`

2022-09-15 00:08 UTC, KatieBuc commented
Thanks @fkiraly - this should address everything now

2022-09-25 20:19 UTC, fkiraly approved these changes
All great! Sorry for not merging, was preparing the release.

2022-09-25 20:19 UTC, merged