Base signature commit.
alan-turing-institute/sktime pull request #714
Opened 2021-03-01 14:46 UTC by jambo6

This PR implements two classes for time series analysis with signatures:

- `GeneralisedSignatureMethod` Transformation class for generating signatures from time-series data.
- `SignatureClassifier` Wraps the above method with a tabular ML classifier.

The structure of the `GeneralisedSignatureMethod` follows closely from [this work in this paper](https://arxiv.org/pdf/2006.00873.pdf).

This adds esig as a soft dependency.

2021-03-13 19:39 UTC, TonyBagnall commented
hi, thanks for updating this PR, its failing some of the automated tests. I'll discuss this with Markus and see if we can suggest solutions, I'd really like this in the toolkit

2021-03-14 12:36 UTC, jambo6 commented
Sorry it's taking ages, there have been a host of issues with each different signature package I tried. 

I should be one esig update away from tests passing though. The only remaining issue is some import fault in esig rather than an installation problem. The developers are aware and it should be sorted in the next update. 

Give me two weeks, then if tests are still not passing we should discuss.

2021-03-14 12:38 UTC, TonyBagnall commented
no problem, I feel you pain :) And no rush, but if you need assistance give us a shout.

2021-06-03 07:39 UTC, jambo6 commented
At long last, everything seems to be working. However, as can be seen, it's not finishing the tests for macos. Do you know whats going wrong here?

2021-06-08 16:28 UTC, mloning commented
Hi @jambo6, GitHub now requires approval from first-time contributors to run CI checks, just approved it now.

2021-06-20 13:56 UTC, fkiraly commented
Quick question: is `SignatureClassifier` not redundant with pipelining that we already have?
I.e., just stick the `GeneralisedSignatureMethod` and classifier together.

2021-06-20 15:34 UTC, TonyBagnall commented
I like to have specific classifiers for transformers for evaluation purposes. For example we put in the RocketClassifier so that we can concretely  point to the classifier we have evaluated. I would prefer it stay in. And @jambo6 well done on sticking with it, we really appreciate the effort involved

2021-06-21 13:37 UTC, jambo6 commented
SignatureClassifier is effectively redundant, but it was so as to keep inline with with other things all having Classifier at the end. I've no strong feelings with regards to how the signature module should be laid out though, so am happy to edit/remove anything if you ever want me to.

Do I need to do anything else for this at the moment?

2021-06-23 21:25 UTC, fkiraly commented
This looks really great!

Looks almost ready to be merged.

Quick remarks:

* you should add new transformers and estimators to `sktime.tests._config` - add the new estimators, and some reasonable parameter combinations
* I like your decorators aroudn `fit` and `predict`. We've been internally disussing how to deal with the various conversions, see the related PR #980 and discussion for forecasting. Perhaps you have some good ideas?

2021-06-23 21:49 UTC, mloning reviewed
Hi @jambo6, really happy that you could sort out the PR! I just have a few minor comments.

Also please:
* add yourself to the `CODEOWNERS` file
* add the main classes to `sktime/docs/api_reference/`

2021-06-23 21:49 UTC, mloning commented on .all-contributorsrc
> +    {
Is this change intended?

2021-06-23 21:49 UTC, mloning commented on sktime/classification/signature_based/_signature_classifier.py
> +    def setup_classification_pipeline(self):
I'd suggest to make this private
```suggestion
    def _setup_classification_pipeline(self):
```

2021-06-23 21:49 UTC, mloning commented on sktime/transformations/panel/signature_based/_signature_method.py
> +_check_soft_dependencies("esig")
Do we need this here?
```suggestion

```

2021-06-23 21:49 UTC, mloning commented on sktime/transformations/panel/signature_based/_signature_method.py
> +    def _assertions(self):
Is this used?

2021-06-24 08:21 UTC, jambo6 commented
> * I like your decorators aroudn `fit` and `predict`. We've been internally disussing how to deal with the various conversions, see the related PR [Forecasting support for multivariate y and multiple input/output types - working prototype #980](https://github.com/alan-turing-institute/sktime/pull/980) and discussion for forecasting. Perhaps you have some good ideas?

Perhaps a file that has a selection of decorators that provide conversions for fit/transform methods to a specific type? For example the decorators convert any pandas input to numpy and convert back. It would be good to have some logic that can convert between sktime formats under the hood, so the code in any fit/transform only needs to consider one particular format. 

@mloning I have updated the docs and made the edits according to your comments.

2021-06-25 11:06 UTC, mloning approved these changes
Thanks for the changes @jambo6 - I'm happy to merge this now once the tests all pass! Does anyone else want to review before we merge?

2021-06-25 11:20 UTC, fkiraly commented
but the tests don't all pass! It somehow destroys the test examples

2021-06-25 11:21 UTC, fkiraly commented
it's just some import error that should be easily fixable, @jambo6

2021-06-25 11:22 UTC, fkiraly requested changes
this is massive but changes are localized and interface compliant.

Looks good, except for the import error mentioned above, which needs fixing before merge.

2021-06-26 12:08 UTC, mloning requested changes

2021-06-26 12:08 UTC, mloning commented on build_tools/run_examples.sh
> +for notebook in examples/*method.ipynb; do
That change is probably not intended?
```suggestion
for notebook in examples/*.ipynb; do
```

2021-06-27 19:07 UTC, TonyBagnall commented
sorry, clustering has introduced minor conflicts I think

2021-06-30 17:12 UTC, mloning approved these changes
I've had a look twice in the last few days, it's a lot of code, but I'm happy to merge this now. 

Really appreciate your work here @jambo6, especially after all the issues with the dependencies!  

Let me know if anyone else wants to review before we merge?

2021-06-30 17:48 UTC, TonyBagnall approved these changes
great job!

2021-06-30 18:20 UTC, fkiraly approved these changes
yes, looks good and tests seem to run

2021-07-01 11:02 UTC, merged

2021-07-01 11:02 UTC, mloning commented
Now merged @jambo6 - thanks again, great work!