Add a GitHub Action script to Automate Issue Assignment to Contributors
alan-turing-institute/sktime pull request #7531
Opened 2024-12-15 16:32 UTC by jgyasu

#### Reference Issues/PRs

Fixes #7528 

#### What does this implement/fix? Explain your changes.

This adds a YAML file in `.github/workflows` which interacts with the GitHub's API and assigns issues to user based on a trigger command, the script is taken from [https://github.com/bdougie/take-action/blob/main/action.yml](https://github.com/bdougie/take-action/blob/main/action.yml)

#### Does your contribution introduce a new dependency? If yes, which one?

#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/sktime/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/sktime/blob/main/.all-contributorsrc) in the `sktime` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] Optionally, for added estimators: I've added myself and possibly to the `maintainers` tag - do this if you want to become the owner or maintainer of an estimator you added.
  See here for further details on the [algorithm maintainer role](https://www.sktime.net/en/latest/get_involved/governance.html#algorithm-maintainers).
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-12-18 16:59 UTC, fkiraly requested changes
Great, thanks!

Some comments:
* can we configur ethis that only "good first issues" are automatically assigned this way?
* maybe difficult to achieve, but there are "umbrella" issues which point to many individual locations, one contributor can pick one location. One example is https://github.com/sktime/sktime/issues/7386 - in this case, only the first contributor could assign themselves. The expected behaviour would be to allow arbitrary numbers of assigned individuals on these, or alternatively one assignment per sub-ticket.
* The used action does not seem to have a lot of dependencies, that is a security and a maintenance risk. Should we perhaps not just make our own action? Especially that we have specific requirements regarding labels?

2024-12-18 17:10 UTC, jgyasu commented
On it!

2024-12-30 15:38 UTC, yarnabrina commented
Question about a hypothetical scenario: if someone assigns themselves, and then do not complete it for bandwidth issues or any other reason, is this also going to de-assign after some stipulated time? This may be more relevant in context of @fkiraly's 1st comment of good-first issues. I see a lot of them showing interest, and then not all of them proceeds to create a PR and someone else requests in future. If issues are already shown as assigned, new contributors may think it's being worked upon by someone else and not considering those anymore?

2024-12-30 16:14 UTC, jgyasu commented
> Question about a hypothetical scenario: if someone assigns themselves, and then do not complete it for bandwidth issues or any other reason, is this also going to de-assign after some stipulated time? This may be more relevant in context of @fkiraly's 1st comment of good-first issues. I see a lot of them showing interest, and then not all of them proceeds to create a PR and someone else requests in future. If issues are already shown as assigned, new contributors may think it's being worked upon by someone else and not considering those anymore?

Hi, thanks for the review. I did think about this. I think this is programmable, we can have a threshold, let's say 15 days of no activity and after that the script will automatically un-assign the the asignee.

2025-01-06 11:58 UTC, fnhirwa reviewed
Adding points on what was said above.

I agree that the first good issues be assigned to the contributors.
In order to extend our responsiveness to issues, it would be more sensible if this automation is further extended to assign remaining issues automatically to core devs. This can apply also for PRs.

2025-01-14 07:43 UTC, fkiraly commented
> In order to extend our responsiveness to issues, it would be more sensible if this automation is further extended to assign remaining issues automatically to core devs. This can apply also for PRs.

Hm, I disagree - this would interfere with planning processes on ticket boards, and assign issues to core devs who may not be working on that module.

2026-05-30 12:41 UTC, closed without merging